name: e_commerce_jktecno
description: "E-commerce app for JK Tecno II selling cell phones."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^15.1.1
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
